# Site settings
title: Pricehare blog
description: >
 An easy way to save money when you shop online. News, updates and money saving advice from the Pricehare team.

# Build settings
markdown: kramdown

# post settings
permalink: /:year/:month/:day/:title/

paginate: 5

prose:
  rooturl: '_posts'
  siteurl: https://blog.pricehare.com'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Description"
          alterable: true
      - name: "keywords"
        field:
          element: "text"
          label: "Meta Keywords"
          placeholder: "Comma seperated"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
      - name: "twitterimage"
        field:
          element: "text"
          label: "Twitter Card Image"
          placeholder: "URL to image"
          alterable: true
