# Site settings
title: Pricehare blog
description: >
 An easy way to save money when you shop online. News, updates and money saving advice from the Pricehare team.

# Build settings
markdown: kramdown

# post settings
permalink: /:year/:month/:day/:title/

paginate: 5